namespace Cortexia.FileManagement.Endpoint.WebAPI.Translators;

public class TranslatorKeys
{
    #region Common

    public const string VALIDATION_ERROR_NOT_EMPTY = nameof(VALIDATION_ERROR_NOT_EMPTY);
    public const string VALIDATION_ERROR_NOT_NULL = nameof(VALIDATION_ERROR_NOT_NULL);
    public const string VALIDATION_ERROR_IS_REQUIRED = nameof(VALIDATION_ERROR_IS_REQUIRED);
    public const string VALIDATION_ERROR_IS_DUPLICATED = nameof(VALIDATION_ERROR_IS_DUPLICATED);
    public const string VALIDATION_ERROR_NOT_FOUND = nameof(VALIDATION_ERROR_NOT_FOUND);
    public const string VALIDATION_ERROR_MUST_BE_UNIQUE = nameof(VALIDATION_ERROR_MUST_BE_UNIQUE);
    public const string VALIDATION_ERROR_NOT_EXIST = nameof(VALIDATION_ERROR_NOT_EXIST);
    public const string VALIDATION_ERROR_MAX_LENGTH = nameof(VALIDATION_ERROR_MAX_LENGTH);
    public const string VALIDATION_ERROR_MIN_LENGTH = nameof(VALIDATION_ERROR_MIN_LENGTH);
    public const string VALIDATION_ERROR_STRING_LENGTH_BETWEEN = nameof(VALIDATION_ERROR_STRING_LENGTH_BETWEEN);
    public const string VALIDATION_ERROR_MAX_VALUE = nameof(VALIDATION_ERROR_MAX_VALUE);
    public const string VALIDATION_ERROR_MIN_VALUE = nameof(VALIDATION_ERROR_MIN_VALUE);
    public const string VALIDATION_ERROR_VALUE_BETWEEN = nameof(VALIDATION_ERROR_MIN_VALUE);
    public const string VALIDATION_ERROR_NOT_EQUAL = nameof(VALIDATION_ERROR_NOT_EQUAL);
    public const string VALIDATION_ERROR_EQUAL = nameof(VALIDATION_ERROR_EQUAL);
    public const string VALIDATION_ERROR_NOT_ACCESS = nameof(VALIDATION_ERROR_NOT_ACCESS);
    public const string VALIDATION_ERROR_NOT_AUTHENTICATED = nameof(VALIDATION_ERROR_NOT_AUTHENTICATED);
    public const string VALIDATION_ERROR_NOT_AUTHORIZED = nameof(VALIDATION_ERROR_NOT_AUTHORIZED);
    public const string VALIDATION_ERROR_NOT_VALID = nameof(VALIDATION_ERROR_NOT_VALID);
    public const string VALIDATION_ERROR_MUST_BE = nameof(VALIDATION_ERROR_MUST_BE);
    public const string VALIDATION_ERROR_FORMAT_INCORRECT = nameof(VALIDATION_ERROR_FORMAT_INCORRECT);

    #endregion
}
